### ISSUE TITLE
ERROR: SyntaxError: Unexpected token function

### ISSUE THREAD

**Issue by duyichao** [Joxroxagain/adidas-bot#5]
hello

after installing I can't start a new project.

get the following

```bash
$ npm start

> adidas-bot@0.1.12 start E:\adidas-bruteforcer
> node index.js

E:\adidas-bruteforcer\index.js:104
async function launchTasks() {
      ^^^^^^^^

SyntaxError: Unexpected token function
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:389:7)
    at startup (bootstrap_node.js:149:9)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! adidas-bot@0.1.12 start: `node index.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the adidas-bot@0.1.12 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\ASUS\AppData\Roaming\npm-cache\_logs\2019-09-21T13_22_22_928Z-debug.log
```

I'm running node v6.11.2
and npm 6.11.3

how can I solved?

**Comment by dlcoffee** [comment]
my guess is you need to upgrade your `node` version. `v6.11.2` is very old, and doesn't support `async/await`.
